import { useState } from 'react'
import { BrainCircuit, Send } from 'lucide-react'
import { useLanguage } from '../i18n'
import { AppShell } from '../components/AppShell'
import { ErrorState, PageHeader } from '../components/Phase2UI'
import { api } from '../services/api'

export function EmployeeAssistantPage() {
  const { language, t } = useLanguage()
  const [message, setMessage] = useState('Explain stratified sampling in simple terms.')
  const [mode, setMode] = useState<'general' | 'document'>('general')
  const [documentId, setDocumentId] = useState('')
  const [answer, setAnswer] = useState<{ answer: string; sources: Record<string, unknown>[]; provider: string } | null>(null)
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const ask = async () => { setBusy(true); setError(''); setAnswer(null); try { const result = await api.assistant({ message, mode, language, ...(mode === 'document' && documentId ? { document_id: Number(documentId) } : {}) }); setAnswer(result) } catch (err) { setError(err instanceof Error ? err.message : 'StatBot could not answer') } finally { setBusy(false) } }
  return <AppShell><div className="animate-rise"><PageHeader eyebrow="StatBot · Learning assistant" title={t('ask')} description="Get a concise general explanation or ground the answer in a processed learning document. Document answers always expose source chunks." /><section className="panel mt-8 max-w-4xl p-6 sm:p-8"><div className="flex items-start gap-3"><span className="status-icon"><BrainCircuit size={19} /></span><div><p className="eyebrow text-teal">Assistant mode</p><h2 className="mt-2 text-xl font-semibold text-navy">Ask a learning question</h2></div></div><div className="mt-6 flex flex-wrap gap-2">{(['general', 'document'] as const).map((item) => <button type="button" key={item} onClick={() => setMode(item)} className={`rounded-full px-4 py-2 text-xs font-bold ${mode === item ? 'bg-navy text-white' : 'bg-slate-100 text-slate-600'}`}>{item === 'general' ? 'General explanation' : 'Document-grounded'}</button>)}</div><label className="mt-5 block"><span className="text-xs font-bold uppercase tracking-wide text-slate-500">Your question</span><textarea className="form-input mt-2 min-h-28" value={message} onChange={(event) => setMessage(event.target.value)} /></label>{mode === 'document' && <label className="mt-4 block"><span className="text-xs font-bold uppercase tracking-wide text-slate-500">Processed document ID</span><input className="form-input mt-2" inputMode="numeric" value={documentId} onChange={(event) => setDocumentId(event.target.value)} placeholder="Example: 1" /></label>}<button type="button" className="primary-button mt-5" disabled={busy || message.trim().length < 2 || (mode === 'document' && !documentId)} onClick={() => void ask()}><Send size={16} />{busy ? t('loading') : t('ask')}</button>{error && <div className="mt-5"><ErrorState message={error} onRetry={() => void ask()} /></div>}{answer && <div className="mt-6 rounded-2xl border border-teal/20 bg-[#f4fbfa] p-5"><div className="flex items-center justify-between gap-3"><p className="text-xs font-bold uppercase tracking-wide text-teal">{answer.provider}</p><span className="rounded-full bg-white px-2.5 py-1 text-[10px] font-bold uppercase text-slate-500">{mode}</span></div><p className="mt-3 text-sm leading-7 text-slate-700">{answer.answer}</p>{answer.sources.length > 0 && <div className="mt-5 border-t border-teal/10 pt-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Sources</p><div className="mt-2 flex flex-wrap gap-2">{answer.sources.map((source, index) => <span className="rounded-full bg-white px-3 py-1.5 text-xs font-semibold text-slate-600" key={index}>Chunk {String(source.chunk_id)}</span>)}</div></div>}</div>}</section></div></AppShell>
}
