import { useEffect, useState } from 'react'
import { Activity, BarChart3, CheckCircle2, Database, Layers3, Target } from 'lucide-react'
import { AppShell } from '../components/AppShell'
import { ErrorState, LoadingState, PageHeader, ScoreBar } from '../components/Phase2UI'
import { useAuth } from '../auth/AuthContext'
import { api } from '../services/api'
import type { CompetencyVector, EvidenceRecord, FRACProfile, VelocityMetrics } from '../types'

export function EmployeeIntelligencePage() {
  const { user } = useAuth()
  const [data, setData] = useState<{ frac: FRACProfile; vector: CompetencyVector; evidence: EvidenceRecord[]; velocity: VelocityMetrics } | null>(null)
  const [error, setError] = useState('')
  const load = async () => {
    if (!user) return
    setError('')
    try {
      const [frac, vector, evidence, velocity] = await Promise.all([api.fracProfile(user.id), api.competencyVector(user.id), api.evidence(user.id), api.velocity(user.id)])
      setData({ frac, vector, evidence, velocity })
    } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load intelligence profile') }
  }
  useEffect(() => { void load() }, [user?.id])
  if (!data) return <AppShell><PageHeader eyebrow="FRAC intelligence · Step 01" title="Capability intelligence" description="Loading your database-traceable role, activity, evidence, and vector profile." />{error ? <ErrorState message={error} onRetry={() => void load()} /> : <LoadingState label="Building FRAC and evidence profile…" />}</AppShell>
  const bySource = data.evidence.reduce<Record<string, number>>((acc, row) => { acc[row.source_type] = (acc[row.source_type] || 0) + 1; return acc }, {})
  return <AppShell><div className="animate-rise"><PageHeader eyebrow="FRAC intelligence · Evidence layer" title="From role to capability vector" description="Your profile is traced from position → role → activities → required competencies. Scores remain evidence-based and confidence-weighted." action={<button type="button" className="secondary-button" onClick={() => void load()}>Refresh profile</button>} />
    <section className="mt-8 grid gap-4 sm:grid-cols-3"><Metric icon={Layers3} label="Position" value={data.frac.position || 'Not mapped'} /><Metric icon={Target} label="Role" value={data.frac.role || 'Not mapped'} /><Metric icon={BarChart3} label="Alignment" value={`${data.vector.overall_alignment_score}%`} /></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1.1fr_0.9fr]"><div className="panel p-6 sm:p-8"><div className="flex items-start gap-3"><span className="status-icon"><Activity size={18} /></span><div><p className="eyebrow text-teal">Role activity chain</p><h2 className="mt-2 text-xl font-semibold text-navy">Required work activities</h2></div></div><div className="mt-6 space-y-3">{data.frac.activities.map((item) => <div className="rounded-xl border border-line p-4" key={`${item.activity_id}-${item.competency_id}`}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-navy">{item.activity}</p><p className="mt-1 text-xs text-slate-500">{item.competency_id === 0 ? 'Unresolved competency' : `Competency #${item.competency_id}`} · {item.criticality}% criticality</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${item.gap >= 30 ? 'bg-red-50 text-red-700' : item.gap > 0 ? 'bg-amber-50 text-amber-700' : 'bg-[#eef7f6] text-teal'}`}>{item.gap > 0 ? `${item.gap} pt gap` : 'On target'}</span></div><div className="mt-4 grid gap-2 text-xs sm:grid-cols-3"><div><span className="text-slate-500">Current</span><p className="mt-1 font-semibold text-navy">{item.current_score}% · Level {item.current_level} ({item.current_level_label})</p></div><div><span className="text-slate-500">Required</span><p className="mt-1 font-semibold text-navy">{item.required_score}% · Level {item.required_level}</p></div><div><span className="text-slate-500">Evidence gap</span><p className="mt-1 font-semibold text-red-700">{item.gap} points</p></div></div><div className="mt-3"><ScoreBar value={item.current_score} target={item.required_score} color={item.gap > 0 ? 'amber' : 'teal'} /></div></div>)}</div></div><div className="panel p-6 sm:p-8"><p className="eyebrow text-teal">Vector alignment</p><h2 className="mt-2 text-xl font-semibold text-navy">Current vs target</h2><div className="mt-6 space-y-4"><div className="flex items-center justify-between text-sm"><span className="text-slate-500">Cosine similarity</span><strong className="text-navy">{data.vector.cosine_similarity}</strong></div><div className="flex items-center justify-between text-sm"><span className="text-slate-500">Weighted distance</span><strong className="text-navy">{data.vector.weighted_distance}</strong></div><div className="border-t border-line pt-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Largest vector gaps</p><div className="mt-4 space-y-3">{data.vector.competency_specific_gaps.filter((item) => item.gap > 0).slice(0, 5).map((item) => <div key={item.competency_id}><div className="flex justify-between text-sm"><span className="font-semibold text-navy">{item.competency}</span><span className="font-bold text-red-600">{item.gap} pts</span></div><div className="mt-1"><ScoreBar value={item.current} target={item.target} color="amber" /></div></div>)}</div></div></div></div></section>
    <section className="mt-6 grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><div className="panel p-6"><p className="eyebrow text-teal">Evidence confidence</p><h2 className="mt-2 text-xl font-semibold text-navy">What supports your score?</h2><div className="mt-5 space-y-3">{Object.entries(bySource).map(([source, count]) => <div className="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3" key={source}><span className="text-sm font-semibold text-navy">{source}</span><span className="text-sm font-bold text-teal">{count} records</span></div>)}</div></div><div className="panel p-6"><div className="flex items-start gap-3"><span className="status-icon"><Database size={18} /></span><div><p className="eyebrow text-teal">Learning telemetry</p><h2 className="mt-2 text-xl font-semibold text-navy">Velocity and activity</h2></div></div><div className="mt-5 grid gap-4 sm:grid-cols-4">{[['Learning velocity', data.velocity.learning_velocity], ['Learning hours', data.velocity.learning_hours], ['Engagement', `${data.velocity.engagement_rate}%`], ['Improvement', `${data.velocity.competency_improvement_rate} pts`]].map(([label, value]) => <div className="rounded-xl border border-line p-4" key={String(label)}><p className="text-lg font-semibold text-navy">{value}</p><p className="mt-1 text-xs text-slate-500">{label}</p></div>)}</div><div className="mt-5 flex items-center gap-2 text-xs text-slate-500"><CheckCircle2 size={14} className="text-teal" />Telemetry is confidence-weighted and cannot silently replace formal assessment evidence.</div></div></section>
  </div></AppShell>
}

function Metric({ icon: Icon, label, value }: { icon: typeof Layers3; label: string; value: string }) { return <div className="panel flex items-center gap-3 p-5"><span className="status-icon"><Icon size={18} /></span><div className="min-w-0"><p className="text-xs uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 truncate text-sm font-semibold text-navy">{value}</p></div></div> }
